### ISSUE TITLE
splitAndAdd doesn't move the existing nodes

### ISSUE THREAD

**Issue by pafgoncalves** [tristanls/k-bucket#11]
From my understanding of the discovery mecanism (https://docs.google.com/presentation/d/11qGZlPWu6vEAhA7p3qsQaQtWH7KofEC9dMeBFZ1gYeA/edit#slide=id.g1718cc2bc_01827 and next slides), the existing nodes should be moved to the respective low/high buckets, and not simply deleted.

**Comment by tristanls** [comment]
Hi @pafgoncalves ,

Hmm... can you provide an example in code that is not doing what you're expecting? It's been a while, but I took a look at `splitAndAdd()` and to me it seems it should be doing the right thing (splitting the bucket, moving the nodes to low and high buckets, and then making itself an "inner node" by not having a bucket):

```javascript
    // redistribute existing contacts amongst the two newly created buckets
    self.bucket.forEach(function (storedContact) {
        if (self.determineBucket(storedContact.id, bitIndex) < 0) {
            self.low.add(storedContact);
        } else {
            self.high.add(storedContact);
        }
    });

    self.bucket = undefined; // mark as inner tree node
```

**Comment by pafgoncalves** [comment]
You are right!
Completely missed the forEach.

**Comment by tristanls** [comment]
Ok, cool. Thank you for bringing it up, it's good to have people double-checking the work :smile:
