### ISSUE TITLE
Remove EventEmitter inheritance

### ISSUE THREAD

**Issue by fanatid** [tristanls/k-bucket#17]
You can remove `EventEmitter` inheritance if allow pass `ping` function through `options` to constructor.

**edit**: with `ping` callback you can remove `root` argument

**Comment by feross** [comment]
I don't think it matters *that* much, but I'm okay with this.

**Comment by tristanls** [comment]
Implemented as of https://github.com/tristanls/k-bucket/releases/tag/v2.0.0

**Comment by fanatid** [comment]
@tristanls Thank you!

**Comment by fanatid** [comment]
Don't we harry with this? I found that events `add` and `remove` would be helpful..

**Comment by tristanls** [comment]
¯\\_(ツ)_/¯
