### ISSUE TITLE
nodes for ping

### ISSUE THREAD

**Issue by fanatid** [tristanls/k-bucket#18]
Should `k-bucket` select nodes for `ping` randomly?
If you always return first `numberOfNodesToPing` nodes in `ping` event, other nodes in bucket may become obsolete.

**Comment by tristanls** [comment]
The reason for not doing a random `ping` is to let the Kademlia network organize around the most reliable nodes.

> But Kademlia’s scheme uses k-buckets, with k nodes. And that’s where its main advantage lies, on a full k-bucket that can’t be split, it can still reorder nodes. The buckets being a list, it orders oldest nodes toward the end. And those will never be dropped unless they stop responding. As older nodes are also the most persistent in the routing table, the network organizes itself around the most reliable points.

-- Internet Archive of the now inaccessible reference: https://web.archive.org/web/20140217064545/http://offthelip.org/?p=157
