### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by fanatid** [tristanls/k-bucket#19]
@tristanls what are you think about [standard](https://github.com/feross/standard/)? or maybe [semistandard](https://github.com/Flet/semistandard)?

**Comment by tristanls** [comment]
I changed my personal code style about three times since this project was created 😄.  I don't expect there to be enough changes to justify rewriting to meet a specific code style.

**Comment by fanatid** [comment]
Agreed, I also changed my code style few times :)
