### ISSUE TITLE
id as argument

### ISSUE THREAD

**Issue by fanatid** [tristanls/k-bucket#26]
`k-bucket` don't need `Object` as argument for `closest`/`get`/`remove`
@tristanls what you think about replace `Object` to `id`? like in method `get`

**Comment by feross** [comment]
@fanatid Then how will one store extra data along with the node? `bittorrent-dht` does this to implement `dht.addNode({ host: '', port: 0})` for example. https://github.com/feross/bittorrent-dht#dhtaddnodenode

**Comment by fanatid** [comment]
@feross I didn't mention `add`.
Only `closest`/`get`/`remove` will be changed, `add` will be only one method who receive `Object`.

**Comment by tristanls** [comment]
It's an API change. I'll hold off on 3.0.0 (post #25 and `TypeError` throws) so that this API change can be included if you want to do a PR for this.
