### ISSUE TITLE
distance as paramter (like arbiter)

### ISSUE THREAD

**Issue by fanatid** [tristanls/k-bucket#36]
It should make `KBucket` more flexible. Thoughts?

**Comment by tristanls** [comment]
Technically, since we're in JavaScript, and `distance` is only used via `KBucket.distance`, it's already parametrizable via monkey patching. For example:
```javascript
const KBucket = require("k-bucket");
KBucket.distance = () => Math.random() * 100;
```

**Comment by tristanls** [comment]
Heh.. I think this highlights the inconsistency of the API though :)

**Comment by fanatid** [comment]
Yes, it will work, but what if we have 2 buckets and want 2 different algorithms for distance?

**Comment by tristanls** [comment]
I agree, parameterized distance would be a way to do that. You are using buckets with 2 different distance algorithms?

**Comment by fanatid** [comment]
> You are using buckets with 2 different distance algorithms?

No.. it's just abstract example.

**Comment by tristanls** [comment]
I think a parameterized distance would make the KBucket API more consistent with itself.

**Comment by tristanls** [comment]
I have some edits I'll promote soon for you to take a look at.

**Comment by tristanls** [comment]
@fanatid here's what I'm thinking. It'll keep the API the same, while incorporating your change, and making the API more self-consistent by exposing `KBucket.arbiter`: https://github.com/tristanls/k-bucket/commit/eb85f46692c9873d6510d5d454c06df9ecf294e9

This also makes next version 3.1.0 instead of 4.0.0.

**Comment by fanatid** [comment]
@tristanls it's really cool!

**Comment by tristanls** [comment]
K, thank you for the feedback. Releasing 3.1.0.
