### ISSUE TITLE
bittorrent-dht tests stall after 3.0.3 update

### ISSUE THREAD

**Issue by feross** [tristanls/k-bucket#38]
Not sure what was in the 3.0.3 update, but now bittorrent-dht (and webtorrent) tests are stalling. If I install k-bucket 3.0.2 then the tests run fine.

I'm looking into this now. But any ideas what the issue could be?

**Comment by feross** [comment]
It looks like the code was substantially modified, so it's not easy to see where the behavior change might be. The effect in bittorrent-dht seems to be that announces fail.

I decided to just lock to version 3.0.2 for the time being.

Any help would be appreciated, @fanatid, @tristanls. Thanks!

**Comment by fanatid** [comment]
@feross bittorrent-dht tests fails?
from my side all fine:
```
$ npm run test-live

> bittorrent-dht@7.3.1 test-live /home/kirill/coloredcoins/bittorrent-dht
> tape test/live/*.js

TAP version 13
# Find peers before ready is emitted
ok 1 Found at least one other DHT node
ok 2 Found at least one peer that has the file
ok 3 Found a peer in 578 ms

1..3
# tests 3
# pass  3

# ok

$ npm ls --depth=0 |grep k-bucket
├── k-bucket@3.0.3
```

**Comment by feross** [comment]
@fanatid Most of our tests are in `npm test`.

**Comment by fanatid** [comment]
Oh, sorry! Now I see that tests not passes.
What about k-rpc? As I understand, this package works fine?

**Comment by feross** [comment]
`k-rpc` tests seem to be fine.

The thing is, `bittorrent-dht` tests passed before the 3.0.3 update, so clearly there was some kind of behavior change in [this commit](https://github.com/tristanls/k-bucket/commit/98f7e46108e1c135f8f52ff033ef356d75012563). Now, maybe `bittorrent-dht` was relying on undocumented behavior of `k-bucket` or something, but it seems unlikely since we only use public APIs.

**Comment by tristanls** [comment]
I've observed the following (after adding some log statements to `bittorrent-dht client.js`):

```
v3.0.3

# announce with implied port
START _closest new KBucket(...)
END _closest new KBucket(...)
START _closest onreply.table.add
END _closest onreply.table.add
START _put this._rpc.queryAll(table.closest(key)...)
RESULT table.closest(infoHash) 
START _closest new KBucket(...)
END _closest new KBucket(...)
END _put this._rpc.queryAll(table.closest(key)...)
START _closest onreply.table.add
END _closest onreply.table.add
... # hang

v3.0.2

# announce with implied port
START _closest new KBucket(...)
END _closest new KBucket(...)
START _closest onreply.table.add
END _closest onreply.table.add
START _put this._rpc.queryAll(table.closest(key)...)
RESULT table.closest(infoHash) [object Object]
END _put this._rpc.queryAll(table.closest(key)...)
START _addPeer this._peers.add [object Object] 6Jo6ugA1BVeDu7nuOukM++LLoB0= [object Object]
END _addPeer this._peers.add [object Object] 6Jo6ugA1BVeDu7nuOukM++LLoB0= [object Object]
ok 7 should be equivalent
```

It appears to me that `table.closest(infoHash)` in v3.0.3 is no longer returning a value (nothing is logged in `RESULT table.closest(infoHash)`, whereas v3.0.2 it returns an object `RESULT table.closest(infoHash) [object Object]`.

**Comment by fanatid** [comment]
I think I know why it's happened.

https://github.com/tristanls/k-bucket/blob/v3.0.2/index.js#L166
`[1,2,3].slice(0, n) // => [1,2,3]` -- where `n = undefined`
https://github.com/tristanls/k-bucket/blob/v3.0.3/index.js#L142
`contacts.length < n // => false` -- where `contacts = []` and `n = undefined`

**Comment by tristanls** [comment]
In the code `n` is documented as required: https://github.com/tristanls/k-bucket/blob/eb85f46692c9873d6510d5d454c06df9ecf294e9/index.js#L136, but that didn't make it to README documentation: https://github.com/tristanls/k-bucket#kbucketclosestid-n , so the documented API does not require `n`.

**Comment by fanatid** [comment]
I think README.md is ok. Optional argument stay in brackets: https://github.com/tristanls/k-bucket/tree/v3.1.0#kbucket_determinenodenode-id-bitindex

**Comment by tristanls** [comment]
`bittorrent-dht` uses `closest(id, n)` method (https://github.com/tristanls/k-bucket#kbucketclosestid-n) without providing `n`: https://github.com/feross/bittorrent-dht/blob/299f0c117dbb42f52c3ffebd311b06a89670e7ea/client.js#L304.

I think making `n` in `closest(id, n)` optional is ok. With the behavior then being that all contacts are returned, sorted according to distance. This is what `bittorrent-dht` seems to expect. And this was the behavior in v3.0.2.

**Comment by fanatid** [comment]
Then `n` will be `Infinity` by default, right?

**Comment by tristanls** [comment]
`n = Infinity` by default sounds right to me.

**Comment by tristanls** [comment]
@fanatid, I misunderstood your earlier comment. You're right about README being ok. I think the problem ended up being that no error was thrown when the second parameter was not provided, so, while the API was documented correctly, the code did not enforce the API contract and accepted `closest` calls without second parameter. This lead to dependent code relying on that behavior... and here we are. :)

I still think making `n` optional is an ok forward. It seems the least disruptive.

**Comment by tristanls** [comment]
@feross I think @fanatid resolved the issue in the [3.2.0 release](https://github.com/tristanls/k-bucket/releases/tag/v3.2.0)

**Comment by feross** [comment]
This is resolved now!

**Comment by feross** [comment]
Thanks for the quick fix, @fanatid and @tristanls! I would have been happy changing the way that we call `.closest()` but this fix works too!
